@startuml

participant "Process" as P
participant "DepositReader"
participant "Validator"
participant "DepositToBagConveter" as B
participant "RdaConverter"
participant "OaiOreConverter"
participant "PidMappingConverter"
participant BagWriter

P -> "DepositReader" : read deposit
P <-- "DepositReader" : deposit
P -> Validator : validate bag
P -> B : write bag
B -> RdaConverter: : convert deposit to RDA
return RDA
B -> "OaiOreConverter": : convert deposit to OAI ORE
return OAI ORE
B -> "PidMappingConverter": : convert deposit to PidMapping
return PidMapping

P <-- B : converted deposit

P -> BagWriter : write bag to some place

@enduml
